version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    restart: always
    ports:
      - 8080:8080
      - 8443:8443

    volumes:
      - ./.certs/server.crt:/etc/x509/https/fullchain.pem
      - ./.certs/server.key:/etc/x509/https/privkey.pem

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: auth.localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: true

      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/fullchain.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/privkey.pem

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres-keycloak
      - mailhog-keycloak
    command:
      - start-dev

  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  mailhog-keycloak:
    image: mailhog/mailhog
    container_name: mailhog-keycloak
    restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data:
