version: "3.7"
services:
 

  postgres-db:
    image: postgres:14.10
    restart: always
    tty: true
    environment:
      POSTGRES_DB: 'databaseClinicPet'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8090:8080'
    depends_on:
 
      - postgres-db

volumes:
  mysql-data:
  postgres-data:
